# [module.hugoVersion]
# min = "0.111.3"

[[module.imports]]
path = "github.com/hbstack/hb"

# [params.hb.preferred-language]

[params.hugopress.modules.hb-preferred-language.attributes.hb-alias-refresh-meta]

[params.hugopress.modules.hb-preferred-language.hooks.hb-alias-head-end]

# [params.hugopress.modules.hb-preferred-language.hooks.body-end]
# cacheable = true
